INSERT INTO VENUE_LEVEL(ID, NAME, PRICE) VALUES(1, 'ORCHESTRA', 100);
INSERT INTO VENUE_LEVEL(ID, NAME, PRICE) VALUES(2, 'MAIN', 75);
INSERT INTO VENUE_LEVEL(ID, NAME, PRICE) VALUES(3, 'BALCONY1', 50);
INSERT INTO VENUE_LEVEL(ID, NAME, PRICE) VALUES(4, 'BALCONY2', 40);

INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (1, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (2, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (3, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (4, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (5, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (6, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (7, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (8, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (9, 1, 'Available', 1);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (10, 1, 'Available', 1);

INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (1, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (2, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (3, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (4, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (5, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (6, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (7, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (8, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (9, 1, 'Available', 2);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (10, 1, 'Available', 2);

INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (1, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (2, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (3, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (4, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (5, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (6, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (7, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (8, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (9, 1, 'Available', 3);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (10, 1, 'Available', 3);

INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (1, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (2, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (3, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (4, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (5, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (6, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (7, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (8, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (9, 1, 'Available', 4);
INSERT INTO SEAT(ID, ROW_ID, STATUS, VENUE_LEVEL_ID) VALUES (10, 1, 'Available', 4);
